#!/bin/bash

#DEPENDENCIES:
#yum -y install gcc openmpi openmpi-devel make

#Memory requirements:
#15000 ~ 4GB
#17000 ~ 5GB


START="1"

if [[ `more my_host.out` == "" ]]
then
	touch my_host.out
else
	echo
	echo "File my_host.out already exist. Do you want overwrite it? (y/n)"
	read risp
	if [[ $risp == "y" ]]
	then
		rm my_host.out
		touch my_host.out
	else
		START="0"
	fi
fi

if [[ $START == "1" ]]
then

module load mpi
mpicc life_hpc2.c -o life_hpc2_ompgnu -O3 -mavx -fopenmp -ftree-vectorize -ftree-vectorizer-verbose=1

	for N in $(echo 1)
	do
		for DIM in $(echo 8192 4096 2048)
		do 
			for COMP in $(echo 500 100 1)
			do
				for THR in $(echo 8 4 2 1)
				do
					CMD="./life_hpc2_ompgnu -t $THR -r $DIM -c $DIM -n $COMP -s 10 -d 0"
					echo "# $CMD" >> my_host.out
					$CMD 2>> my_host.out
				done
			done
		done
	done
fi
