#!/bin/bash

FIRST=$(qsub -v type=acc-mpi -o life_acc_mpi.out acc_mpi.qsub)
echo $FIRST
SECOND=$(qsub -W depend=afterany:$FIRST -v type=host-icc-mpi -o life_host_mpi.out host_mpi.qsub)
echo $SECOND
THIRD=$(qsub -W depend=afterany:$SECOND -v type=mic-mpi -o life_mic_mpi.out mic_mpi.qsub)
echo $THIRD
FOURTH=$(qsub -v type=acc-mpi-nc -o life_acc_mpi.out acc_mpi_comm.qsub)
echo $FOURTH
FIFTH=$(qsub -W depend=afterany:$FIRST -v type=host-icc-mpi-nc -o life_host_mpi_comm.out host_mpi.qsub)
echo $FIFTH
SIXTH=$(qsub -W depend=afterany:$SECOND -v type=mic-mpi-nc -o life_mic_mpi_comm.out mic_mpi.qsub)
echo $SIXTH

