#!/bin/bash

FIRST=$(qsub -v type=acc -o life_acc_perf.out acc.qsub)
echo $FIRST
SECOND=$(qsub -W depend=afterany:$FIRST -v type=host-icc -o life_host_perf.out host.qsub)
echo $SECOND
THIRD=$(qsub -W depend=afterany:$SECOND -v type=mic -o life_mic_perf.out mic.qsub)
echo $THIRD
FOURTH=$(qsub -W depend=afterany:$THIRD -v type=acc-mpi -o life_acc_mpi.out acc_mpi.qsub)
echo $FOURTH
FIFTH=$(qsub -W depend=afterany:$FOURTH -v type=host-icc-mpi -o life_host_mpi.out host_mpi.qsub)
echo $FIFTH
SIXTH=$(qsub -W depend=afterany:$FIFTH -v type=mic-mpi -o life_mic_mpi.out mic_mpi.qsub)
echo $SIXTH
SEVENTH=$(qsub -W depend=afterany:$SIXTH -v type=acc-mpi-nc -o life_acc_mpi_comm.out acc_mpi.qsub)
echo $SEVENTH
EIGHTH=$(qsub -W depend=afterany:$SEVENTH -v type=host-icc-mpi-nc -o life_host_mpi_comm.out host_mpi.qsub)
echo $EIGHTH
NINTH=$(qsub -W depend=afterany:$EIGHTH -v type=mic-mpi-nc -o life_mic_mpi_comm.out mic_mpi.qsub)
echo $NINTH

