#!/bin/bash
#PBS -j oe
#PBS -N life_host_mpi
#PBS -o life_hpc_host_mpi.out
#PBS -l select=8:ncpus=16:mem=5gb:cpuspeed=3Ghz
#PBS -q parallel
#PBS -A CON13_INFN
        
module load pgi openmpi/1.6.5--pgi--14.1

#ulimit -m
cd ~/game-of-life 

#echo "#`cat $PBS_NODEFILE`"

for N in $(echo 8 4 1)
do
for DIM in $(echo 17000 8000 4000 2000 1000 )
do 
for COMP in $(echo 1000 0)
do
CMD="mpirun -np $N ./life_hpc2_ompicc -t 16 -r $DIM -c $DIM -n $COMP -s 10 -d 0"
echo "# $CMD"
eval $CMD
done
done
done
